// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnxq1_GrA3PixNgu00jLsWL8o-pIl2SU',
    appId: '1:1090072552325:android:5121ff7bdde9ad900fdaec',
    messagingSenderId: '1090072552325',
    projectId: 'shred-2e198',
    storageBucket: 'shred-2e198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWmbvZMhEcF1tfaiV1WfaJtYtmr5HwDA',
    appId: '1:1090072552325:ios:2a5e04fee7f6bd4d0fdaec',
    messagingSenderId: '1090072552325',
    projectId: 'shred-2e198',
    storageBucket: 'shred-2e198.appspot.com',
    androidClientId: '1090072552325-18qjk27nlvhd50013ro0i79ojgkgeqfv.apps.googleusercontent.com',
    iosClientId: '1090072552325-p08n61n2mfqn1bujagm3hcdm8jg2kmbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shded',
  );
}
